name: pattern_text_editing_controller
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/GeceGibi/pattern_text_editing_controller

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:

